version: '3.7'

services:

  reducer:
    environment:
      - GET_HOSTS_FROM=dns
      - ALLIANCE_UID=${ALLIANCE_UID}
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/client
    command: "sh -c 'sleep 10 && fedn run reducer'"
    volumes:
      - ./test/${EXAMPLE}/combiner:/app/client
    #  - ./sdk:/app/sdk
    #  - ./cli:/app/cli
